name: Build

on: 
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'
      - 'action.yml'

jobs:
  shellcheck:
    name: Check
    uses: ./.github/workflows/check.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: shellcheck
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - 
      name: Get previous tag
      id: previousTag
      run: |
        name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -1)
        echo "previousTag: $name"
        echo "previousTag=$name" >> $GITHUB_ENV
    -
      name: Generate changelog
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        fromTag: ${{ github.ref_name }}
        toTag: ${{ env.previousTag }}
        writeToFile: false
        reverseOrder: true
        includeInvalidCommits: true
        excludeTypes: "docs,build,chore"
    -
      name: Create a release
      uses: action-pack/github-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      with:
        tag: "v${{ vars.MAJOR }}.${{ vars.MINOR }}"
        title: "v${{ vars.MAJOR }}.${{ vars.MINOR }}"
        body: |
          ${{ steps.changelog.outputs.changes }}

          **Full Changelog**: https://github.com/${{ github.repository }}/compare//${{ env.previousTag }}...v${{ vars.MAJOR }}.${{ vars.MINOR }}
    -
      name: Update major release
      uses: action-pack/github-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      with:
        tag: "v${{ vars.MAJOR }}"
        title: "v${{ vars.MAJOR }}"
        body: "See https://github.com/${{ github.repository }}/releases/tag/v${{ vars.MAJOR }}.${{ vars.MINOR }}"
    -
      name: Increment version variable
      uses: action-pack/bump@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
